# Generated by Django 4.1.1 on 2022-09-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Slug',
            field=models.SlugField(blank=True, max_length=267, unique=True),
        ),
    ]
